spring:
  application:
    name: Lab1_2
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/oauth2/jwks

springdoc:
  swagger-ui:
    url: /api-specs/cosmo-cats-product-api.yml

feature:
  cosmo-cats:
    enabled: true
  kitty-products:
    enabled: true
